name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir bin && echo "success"
    - name: cd
      run: cd bin && echo "success"
    - name: pwd
      run: pwd
    - name: generate Makefile
      run: cmake .. && echo "success"
    - name: make && echo "success"
      run: make
    - name: make test && echo "success"
      run: make test
