name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: mkdir
      run: mkdir bin
      
    - name: generate Makefile
      run: cmake ..
      working-directory: bin
    - name: make 
      run: make
      working-directory: bin
    - name: make test
      run: make test
      working-directory: bin
