name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: mkdir
      run: mkdir bin && echo "success"
      
    - name: pwd
      run: pwd
    - name : ls
      run: ls .
    - name: generate Makefile
      run: cmake .. && echo "success"
      working-directory: bin
    - name: make && echo "success"
      run: make
      working-directory: bin
    - name: make test && echo "success"
      run: make test
      working-directory: bin
